---

# Configuration Restic pour tests Molecule
# Utilise un backend local pour éviter les dépendances S3

restic_version: "0.18.1"

# Repository configuration pour les tests
restic_repository_type: "local"
restic_repository_url: "/tmp/restic-test-repo"

# Repository password pour les tests
restic_repository_password: "test-password-123"

# Pas de credentials cloud nécessaires pour les tests locaux
restic_aws_access_key_id: ""
restic_aws_secret_access_key: ""

# Email notifications désactivées pour les tests
restic_notification_email: ""
restic_smtp_server: "localhost"
restic_smtp_port: 25

# Paths à sauvegarder pour les tests
restic_backup_paths:
  - "/etc/hostname"
  - "/etc/os-release"

# Database backup commands pour les tests (vide)
restic_database_backups: []

# Patterns d'exclusion basiques pour les tests
restic_exclude_patterns:
  - "*.tmp"
  - "*/tmp/*"

# Politique de rétention pour les tests
restic_keep_within_daily: "7d"
restic_keep_within_weekly: "2w"
restic_keep_within_monthly: "1m"


# Fail2ban configuration for development/test environment
fail2ban_custom_jails: {}
fail2ban_bantime: "1h"
fail2ban_findtime: "10m"
fail2ban_maxretry: 10

# Firewall UFW configuration for development/test environment
ufw_enabled: true
ufw_docker_enabled: true
ufw_ddos_enabled: true
ufw_logging: "low"

# Anti-DDoS protection settings for development
ufw_ddos_syn_limit: "30/minute"
ufw_ddos_syn_burst: "25"
ufw_ddos_icmp_limit: "2/second"
ufw_ddos_icmp_burst: "3"
ufw_ddos_udp_limit: "60/minute"
ufw_ddos_udp_burst: "25"
ufw_ddos_conn_limit: "25"

# Whitelisted ports for development
ufw_whitelisted_in_ports_base:
  - { to_port: 22, proto: tcp, from_ip: "192.168.0.0/16" }  # SSH depuis réseau local
  - { to_port: 80, proto: tcp }                             # HTTP
  - { to_port: 443, proto: tcp }                            # HTTPS
  - { to_port: 9090, proto: tcp, from_ip: "127.0.0.1" }     # Prometheus local seulement

# IPs à bloquer pour les tests
ufw_blacklisted_ips: []
