---

- name: Deploy Restic backup system
  hosts: all:!localhost
  become: yes
  pre_tasks:
    - name: Check swap device
      ansible.builtin.command: swapon --show=NAME --raw --noheadings
      register: swap_device
      ignore_errors: true
      changed_when: false
      tags: always
  tasks:
    - name: Include periodic tasks
      ansible.builtin.include_tasks: tasks/periodic_tasks.yml
      loop: "{{ periodic_tasks | default({}) | dict2items }}"
      tags: [ "periodic" ]
  roles:
    - { role: restic, tags: [ "backup", "restic" ] }
    - { role: fail2ban, tags: [ "fail2ban" ] }
    - { role: geerlingguy.swap, tags: [ "swap" ], when: swap_device.rc == 0 and not (swap_device.stdout | regex_search('^/dev')) }
    - { role: node_exporter, tags: [ "node_exporter" ], when: monit_client_name is defined and monit_project_name is defined and monit_host_name is defined }
    - { role: loki, tags: [ "loki" ], when: monit_client_name is defined and monit_project_name is defined and monit_host_name is defined }

#- name: Generate Prometheus targets
#  hosts: # TODO
#  become: true
#  tasks:
#    - name: Include generate Prometheus targets task
#      ansible.builtin.include_tasks:
#        file: tasks/generate_prometheus_targets.yml
#        apply:
#          tags: [ "never", "prometheus" ]
#      tags: [ "prometheus" ]
