---
# Example playbook to deploy Fail2ban security
- name: Deploy Fail2ban security system
  hosts: all
  become: yes
  roles:
    - fail2ban

# Rôle Ansible Fail2ban
  post_tasks:
    - name: Display fail2ban status
      command: fail2ban-client status
      register: fail2ban_status
      changed_when: false

    - name: Show active jails
      debug:
        msg: "{{ fail2ban_status.stdout_lines }}"

    - name: Display protected services summary
      debug:
        msg:
          - "SSH Protection: {{ fail2ban_ssh_enabled | default(true) }}"
          - "Nginx Protection: {{ fail2ban_nginx_enabled | default(false) }}"
          - "Apache Protection: {{ fail2ban_apache_enabled | default(false) }}"
          - "FTP Protection: {{ fail2ban_ftp_enabled | default(false) }}"
          - "SFTP Protection: {{ fail2ban_sftp_enabled | default(false) }}"
