---
# Installation des packages requis
- name: Install required packages
  import_tasks: packages.yml

# Création de l'utilisateur et des répertoires
- name: Create restic user and directories
  import_tasks: user.yml

# Installation du binaire Restic
- name: Download and install restic binary
  import_tasks: install.yml

# Configuration des scripts et fichiers
- name: Configure restic scripts and files
  import_tasks: config.yml

# Configuration des services systemd
- name: Setup systemd services and timers
  import_tasks: systemd.yml

# Initialisation du dépôt Restic
- name: Initialize restic repository
  import_tasks: repository.yml
