---
- name: Create systemd service file
  template:
    src: restic-backup.service.j2
    dest: /etc/systemd/system/restic-backup.service
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
  tags:
    - restic

- name: Create systemd timer file
  template:
    src: restic-backup.timer.j2
    dest: /etc/systemd/system/restic-backup.timer
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
  tags:
    - restic

- name: Enable and start restic backup timer
  systemd:
    name: restic-backup.timer
    enabled: yes
    state: started
    daemon_reload: yes
  tags:
    - restic
