---
- name: Create restic group
  group:
    name: "{{ restic_group }}"
    system: yes
  tags:
    - restic

- name: Create restic user
  user:
    name: "{{ restic_user }}"
    group: "{{ restic_group }}"
    system: yes
    shell: /bin/false
    home: "{{ restic_scripts_path }}"
    create_home: yes
    password_lock: yes
  tags:
    - restic

- name: Create restic directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: "0755"
  loop:
    - "{{ restic_scripts_path }}"
    - "{{ restic_cache_path }}"
    - "{{ restic_scripts_path }}/scripts"
    - "{{ restic_scripts_path }}/dumps"
  tags:
    - restic
