---

# Création de l'utilisateur et des répertoires
- name: Setup promtail user and directories
  import_tasks: user.yml

# Installation du binaire Promtail
- name: Install promtail binary
  import_tasks: install.yml

# Configuration des fichiers
- name: Configure promtail
  import_tasks: config.yml

# Configuration du service systemd
- name: Setup promtail systemd service
  import_tasks: systemd.yml
