---
# Création de l'utilisateur et des groupes
- name: Create promtail user group
  ansible.builtin.group:
    name: "{{ group_id }}"
    state: present
  become: true

- name: Create promtail user
  ansible.builtin.user:
    name: "{{ user_id }}"
    group: "{{ group_id }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{ user_id }} nologin User"
    createhome: "no"
    state: present

- name: Add promtail user to adm group
  ansible.builtin.user:
    name: "{{ user_id }}"
    groups: adm
    append: yes

- name: Create promtail directory
  ansible.builtin.file:
    path: "/etc/promtail"
    state: directory
    owner: "{{ user_id }}"
    group: "{{ group_id }}"
    mode: 0755
