---
# Configuration du service systemd
- name: Copy systemd service file
  ansible.builtin.template:
    src: init.service.j2
    dest: "/etc/systemd/system/{{ node_exporter_service_name }}.service"
    owner: "{{ node_exporter_user_name }}"
    group: "{{ node_exporter_group_name }}"
    mode: 0644
  notify: Restart node_exporter

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start node_exporter service
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
    enabled: yes
    state: started
