---
galaxy_info:
  author: Victor Ely
  description: Role to install and configure Restic backup system with automated scheduling
  company: ""
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Fedora
      versions:
        - 35
        - 36
        - 37
  galaxy_tags:
    - backup
    - restic
    - systemd
    - automation
    - s3
    - backblaze

dependencies: []
