---
galaxy_info:
  author: Victor Ely
  description: UFW Firewall configuration role
  company: ""
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - firewall
    - ufw
    - security

dependencies: []
